# Generated by Django 4.2.20 on 2025-03-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2bj', '0002_rename_zaklady_bets_rename_bonusy_bonus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Payments',
        ),
    ]
