# Generated by Django 5.1.3 on 2025-04-06 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("b2bj", "0005_initial"),
        ("payments", "0005_alter_payment_user_alter_paymenttype_transaction_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bets",
            name="game",
        ),
        migrations.RemoveField(
            model_name="bets",
            name="user",
        ),
        migrations.RemoveField(
            model_name="bonus",
            name="user",
        ),
        migrations.RemoveField(
            model_name="statistics",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.DeleteModel(
            name="Game",
        ),
        migrations.DeleteModel(
            name="Bets",
        ),
        migrations.DeleteModel(
            name="Bonus",
        ),
        migrations.DeleteModel(
            name="Statistics",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
