# Generated by Django 5.1.3 on 2025-04-05 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="game",
            name="release_date",
        ),
        migrations.AddField(
            model_name="game",
            name="description",
            field=models.TextField(default="Default Description"),
        ),
        migrations.AddField(
            model_name="game",
            name="game_icon",
            field=models.ImageField(default="static/images/logo.png", upload_to=""),
        ),
        migrations.AlterField(
            model_name="bet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
