# Generated by Django 5.1.3 on 2025-04-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_remove_game_genre_remove_game_release_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
