# Generated by Django 5.1.3 on 2025-04-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_remove_playerprofile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="games_played",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="games_won",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="total_winnings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
