# Generated by Django 5.1.3 on 2025-04-06 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_alter_payment_user_alter_paymenttype_transaction_fee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymenttype",
            old_name="transaction_fee",
            new_name="transaction_fee_percent",
        ),
    ]
