# Generated by Django 5.1.3 on 2025-04-05 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0002_alter_bonus_user"),
        ("games", "0002_remove_game_genre_remove_game_release_date_and_more"),
        ("payments", "0003_alter_payment_user"),
        ("user", "0002_player"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
